Tk
TomaszJakubCodingCorp/Carhub.Lib pull request #2
Opened 2024-09-24 15:00 UTC by TomaszKrasienko

2024-09-24 17:35 UTC, JacquesM27 requested changes

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Serializing/RabbitMqSerializer.cs
> +    private readonly JsonSerializerSettings _settings = new()
to może być constem

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/RabbitMqEventPublisher.cs
> +        return Task.CompletedTask;
nie lepiej to na voida zamienić? publish w cliencie też jest voidowy.

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Conventions/Convention.cs
> +internal sealed class Convention(string exchange, string routingKey) : IConvention
A może `internal sealed recordConvention(string Exchange, string RoutingKey);` bez interfejsu. To i tak tylko prosty obiekcik.

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Clients/RabbitMqClient.cs
> +            _logger.LogInformation($"Published message with ID: {properties.MessageId} to EXCHANGE: '{convention.Exchange}' with routing key: '{convention.RoutingKey}'");
loggery zamiast interpolacji powinny mieć paramsy po przecinku

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Clients/RabbitMqClient.cs
> +    private IBasicProperties CreateMessageProperties(IModel channel, Guid? messageId)
static

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Configuration/Extensions.cs
> +        ConsumersCollection consumersCollection = new ConsumersCollection();
vara zrób 😄

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Connections/ConsumerConnection.cs
> +internal sealed class ConsumerConnection(IConnection connection)
nie rejestrujesz ich do kontenera di? Robisz potem get required service. To się nie wywali?

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Connections/ProducerConnection.cs
> +internal sealed class ProducerConnection(IConnection connection)
To podobnie jak Consumer.

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumerRegistryExtension.cs
> +            .AddHostedService<RabbitMqBackgroundService<TMessage>>(sp =>
`<RabbitMqBackgroundService<TMessage>>` jest chyba niepotrzebne

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/RabbitMqBackgroundService.cs
> +internal class RabbitMqBackgroundService<TMessage> : BackgroundService where TMessage : class
sealed

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +    private readonly Dictionary<Type, object> _consumers = new Dictionary<Type, object>();
samo `[]` wystarczy zamiast `new...`

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +            genericMethod.Invoke(null, new[] { services, consumer.Value });
opcjonalnie możesz zrobić `[services, consumer.Value]` zamiast `new[] { services, consumer.Value }`

2024-09-24 17:35 UTC, JacquesM27 commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +    public void Build(IServiceCollection services)
internal

2024-09-25 05:59 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +            genericMethod.Invoke(null, new[] { services, consumer.Value });
Nie mogę
Krzyczy compiler

2024-09-25 05:59 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +    public void Build(IServiceCollection services)
done

2024-09-25 05:59 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/ConsumersCollection.cs
> +    private readonly Dictionary<Type, object> _consumers = new Dictionary<Type, object>();
done

2024-09-25 06:00 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Consumers/RabbitMqBackgroundService.cs
> +internal class RabbitMqBackgroundService<TMessage> : BackgroundService where TMessage : class
słusznie, done

2024-09-25 06:02 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Clients/RabbitMqClient.cs
> +    private IBasicProperties CreateMessageProperties(IModel channel, Guid? messageId)
done

2024-09-25 06:04 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Clients/RabbitMqClient.cs
> +            _logger.LogInformation($"Published message with ID: {properties.MessageId} to EXCHANGE: '{convention.Exchange}' with routing key: '{convention.RoutingKey}'");
done

2024-09-25 06:05 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Conventions/Convention.cs
> +internal sealed class Convention(string exchange, string routingKey) : IConvention
Still, pozostawiłbym z abstrakcją. Następny serwis nie musi wiedzieć co się dzieje w środku

2024-09-25 06:06 UTC, TomaszKrasienko commented on src/Carhub.Lib.MessageBrokers.RabbitMq/Serializing/RabbitMqSerializer.cs
> +    private readonly JsonSerializerSettings _settings = new()
To nie może być constem

2024-09-25 16:22 UTC, JacquesM27 approved these changes

2024-10-05 13:41 UTC, merged